// 千篇万律·美食推荐（广州站）
// 数据由群友推荐 + 管理员维护
// 最后更新: 2026-07-01

var RESTAURANTS = [
  {
    "name": "好客家·客家艺术厨房概念店(K11店)",
    "address": "珠江东路6号K11购物艺术中心负一层B133铺",
    "scene": "商务宴请",
    "cuisine": "客家菜",
    "avgPrice": 79,
    "rating": null,
    "dishes": "",
    "phone": "(020) 8883 5332",
    "recommender": "",
    "comment": "",
    "minefield": false,
    "minefieldNote": "",
    "lat": 23.113703,
    "lng": 113.333289
  },
  {
    "name": "和苑·精致粤菜(珠江新城店)",
    "address": "花城大道68号环球都会广场3楼",
    "scene": "商务宴请",
    "cuisine": "粤菜",
    "avgPrice": 177,
    "rating": null,
    "dishes": "",
    "phone": "(020) 8306 3668",
    "recommender": "",
    "comment": "",
    "minefield": false,
    "minefieldNote": "",
    "lat": 23.117813,
    "lng": 113.327429
  },
  {
    "name": "南海渔村（珠江新城店）",
    "address": "珠江东路高德置地秋广场F座4楼11号",
    "scene": "商务宴请",
    "cuisine": "粤菜",
    "avgPrice": 168,
    "rating": null,
    "dishes": "",
    "phone": "（020）8398 3188",
    "recommender": "",
    "comment": "",
    "minefield": false,
    "minefieldNote": "",
    "lat": 23.120589,
    "lng": 113.32724
  },
  {
    "name": "陶陶居·雅园(凯华国际店)",
    "address": "珠江新城冼村路5号凯华国际中心6楼",
    "scene": "商务宴请",
    "cuisine": "粤菜",
    "avgPrice": 145,
    "rating": null,
    "dishes": "",
    "phone": "（020）8852 1688",
    "recommender": "",
    "comment": "",
    "minefield": false,
    "minefieldNote": "",
    "lat": 23.117236,
    "lng": 113.327314
  },
  {
    "name": "木棉·醉心粤味(高德置地店)",
    "address": "珠江东路16号高德置地冬广场4楼407号",
    "scene": "商务宴请",
    "cuisine": "粤菜",
    "avgPrice": 108,
    "rating": null,
    "dishes": "",
    "phone": "(020) 8759 0092",
    "recommender": "",
    "comment": "",
    "minefield": false,
    "minefieldNote": "",
    "lat": 23.119298,
    "lng": 113.326737
  },
  {
    "name": "头啖汤·30年老字号广府粤菜(冼村路店)",
    "address": "冼村路92号利雅湾C栋5楼",
    "scene": "商务宴请",
    "cuisine": "粤菜",
    "avgPrice": 104,
    "rating": null,
    "dishes": "",
    "phone": "(020) 3839 9638",
    "recommender": "",
    "comment": "",
    "minefield": false,
    "minefieldNote": "",
    "lat": 23.116666,
    "lng": 113.328509
  },
  {
    "name": "炳胜品味（珠江新城店）",
    "address": "珠江新城冼村路2号1-4楼（省博物馆对面）",
    "scene": "商务宴请",
    "cuisine": "粤菜",
    "avgPrice": 129,
    "rating": null,
    "dishes": "",
    "phone": "（020）3803 5888",
    "recommender": "",
    "comment": "",
    "minefield": false,
    "minefieldNote": "",
    "lat": 23.114951,
    "lng": 113.328645
  },
  {
    "name": "海门鱼仔·潮汕味（冼村店）",
    "address": "兴盛路6号君茂广场2楼（停车到B3层5-6号电梯直达）",
    "scene": "商务宴请",
    "cuisine": "潮汕菜",
    "avgPrice": 103,
    "rating": null,
    "dishes": "",
    "phone": "13622885976",
    "recommender": "",
    "comment": "",
    "minefield": false,
    "minefieldNote": "",
    "lat": 23.120363,
    "lng": 113.328772
  },
  {
    "name": "丘大·鹅仔江景酒家",
    "address": "越秀区沿江中路298号阳光天地3楼",
    "scene": "商务宴请",
    "cuisine": "粤菜",
    "avgPrice": 50,
    "rating": null,
    "dishes": "鹿肉烧卖、手打羊肉烧卖、鹅仔虾饺皇、海胆干蒸烧卖、黑椒蒸牛仔骨、香煎马蹄龟苓膏、擂沙双皮奶蛋挞",
    "phone": "（020）84889921",
    "recommender": "",
    "comment": "",
    "minefield": false,
    "minefieldNote": "",
    "lat": 23.114944,
    "lng": 113.277909
  },
  {
    "name": "大鸽饭(兴盛路店)",
    "address": "兴盛路6号君茂广场3楼",
    "scene": "商务宴请",
    "cuisine": "粤菜",
    "avgPrice": 116,
    "rating": null,
    "dishes": "干逼海味粉丝煲、头菜蒸梅肉饼、米糕拼艾糍、菜心远炒鸽杂、小炒黄牛肉、石板黑椒牛仔粒",
    "phone": "(020)3605 5085",
    "recommender": "",
    "comment": "",
    "minefield": false,
    "minefieldNote": "",
    "lat": 23.120363,
    "lng": 113.328772
  }
];
